[[main]]
  identifier = "wiki"
  name = "Wiki"
  pageRef = "/wiki/"
  weight = 10

[[main]]
  identifier = "tutorials"
  name = "Tutorials"
  pageRef = "/tutorials/"
  weight = 20

[[main]]
  identifier = "posts"
  name = "Posts"
  pageRef = "/posts/"
  weight = 30

[[main]]
  identifier = "journal"
  name = "Journal"
  pageRef = "/journal/"
  weight = 40

[[main]]
  identifier = "tags"
  name = "Tags"
  pageRef = "/tags/"
  weight = 50

[[main]]
  identifier = "about"
  name = "About"
  pageRef = "/about/"
  weight = 60
